name: 'Terraform Build DevOps01-Project'

on:
  push:
    branches:
      - "main"

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:

  tfsec-security-check:
    name: TFSec Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: tfsec
        uses: tfsec/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif

  terraform-plan-lambda-function:
    name: 'TF Plan Lambda Function'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: plan
    needs: [tfsec-security-check]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.6"

      - name: tf init lambda
        run: terraform init
        working-directory: .

      - name: tf plan lambda
        run: terraform plan -out=tfplan
        working-directory: .

      - name: Upload plan as artifact
        uses: actions/upload-artifact@v2
        with:
          name: TF plan lambda
          path: tfplan

  terraform-apply-lambda-function:
    name: 'TF Apply Lambda Function'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: dev
    needs: [terraform-plan-lambda-function]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download plan artifact
        uses: actions/download-artifact@v2
        with:
          name: TF plan lambda
          path: .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.6"

      - name: tf apply lambda
        run: terraform apply tfplan
        working-directory: .
