name: 'Terraform Build DevOps01-Project'

# This workflow will run when there is a push or a pull request to the 'main' branch.
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

# permission can be added at job level or workflow level
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  # Terraform job for setting up AWS resources
  
  terraform:
    name: 'TF GitHub Actions DevOps01-Project'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest # Specifies the runner environment to use

    # Specifies default settings for the shell in all run steps in this job.
    defaults:
      run:
        shell: bash

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-north-1
          role-to-assume: ${{ secrets.ROLE_ARN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.1"
          
  lambda_function:
    needs: [terraform]  # This ensures it runs after the Terraform job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: tf init lambda
        run: terraform init
        working-directory: ./aws_lambda_LMS

      - name: tf plan lambda
        run: terraform plan -out=tfplan
        working-directory: ./aws_lambda_LMS

      - name: Upload plan as artifact
        uses: actions/upload-artifact@v2
        with:
          name: TF plan lambda
          path: aws_lambda_LMS/plan_output.json

      - name: tf apply lambda
        run: terraform apply tfplan
        working-directory: ./aws_lambda_LMS
        if: github.ref == 'refs/heads/main'
